### PR TITLE
Issue 204 fix quiz submission bug

### LINKED ISSUE #204: Fix quiz submission bug
## Currently there is a bug whereby upon quiz submission, the user is redirected back to the quiz start page

A few tests should be created
- after a quiz is submitted the user should be redirected to /quiz not /quiz/[id]
- does the restart un-submit the quiz attempt?
- does the restart create another quiz attempt when you click start?
- how does the restart affect the quiz-attempts page in dashboard/results/[id]/quiz-attempts/

### PR DESCRIPTION
**Pull request by ErikaKK**
## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
Fixed some bugs:
- after a comp is submitted the user should be redirected to `/quiz` not `/quiz/[id]`
    - does the restart un-submit the quiz attempt? **No**
    - does the restart create another quiz attempt when you click start? **No**
    - how does the restart affect the quiz-attempts page in dashboard/results/[id]/quiz-attempts/? **Won't affect anything bc it's not a restart, the server will not allow a second attempt for the same comp**
-  student view sidebar didn't show
-  quiz app `view.py` didn't filter competition properly.
- the mobile view navbar shows `login` instead of `dashboard`.
- visitors can access competition.
- when a comp has already finished, you can still start the quiz
- Once a student submitted a comp, can still start the comp (will get 400 from server)
-  couldn't get matching user id from student model

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**
Still needs to be done:
- quiz model `status` field is very hard to understand. Considering replace it with filtering date `is_comp` and `visible` field
- didn't have attempts in the sidebar for students. It seems we haven't implemented this feature
- when the question is the last one in a practice quiz, this `next` button should change to `submit`
- answer is auto filled for same question in comp. Will it only store one attempt for each question?
- TODOs in comp components

# Related issue

- Resolve #204

### CODE REVIEW

File: client/src/components/ui/Quiz/comp-start.tsx [hunk 1]
```diff
@@ -182,8 +182,7 @@ export function CompStart({
           });
         window.alert("Your answers have been submitted successfully.");
         // refresh the page to get the latest data
-        window.location.reload();
-        router.push("/");
+        window.location.href = "/quiz";
```
Comment (AarifLamat) [inline client/src/components/ui/Quiz/comp-start.tsx:185]: can you remove the comment here since it's no longer relevant pls

**Review by AarifLamat — APPROVED** [review]
good work!
