### PR TITLE
Issue 182 Fix bugs for competition/practice and results pages

### LINKED ISSUE #182: Bug Fixes Competition and Results Pages
## Basic Information
1. **Competition/Practice Page:**  
- Reuse `LatexInput` component to prevent multiple CSS imports.  
- Fix incorrect `attempt_id` when submitting data.  
- Resolve `500 Internal Server Error` for backend `/submit` action.

2. **Results & Rankings Page:**  
- Improve UI for `Table` component in Data Grid.  
- Fix incorrect pagination route navigation.

## Other Information  
- Review frontend component structure for better reusability.  
- Check backend logs for `/submit` failures and refine error handling.

### PR DESCRIPTION
**Pull request by loklokyx**
## Change Summary
- Reuse LatexInput component to avoid redundant CSS imports on competition/practice page
- Fix incorrect attempt_id on data submission
- Resolve 500 error on backend /submit action
- Enhance UI for data-grid Table component on results & rankings page
- Fix incorrect pagination route on results & rankings page

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [Y] The pull request title has an issue number
- [Y] The change works by "Smoke testing" or quick testing
- [N] The change has tests
- [N] The change has documentation

# Related issue

- Resolve #182

### CODE REVIEW

File: client/src/components/ui/Question/preview-modal.tsx [hunk 1]
```diff
@@ -18,6 +15,7 @@ import {
   DialogTitle,
   DialogTrigger,
 } from "@/components/ui/dialog";
+import { LatexInput } from "@/components/ui/math-input";
```
Comment (yunho7687) [inline client/src/components/ui/Question/preview-modal.tsx:18]: this component will send a request to /api/render-tikz which will be route to django server and will lead to a error response. the request is for rendering a png , but for now seems we don't need that as we support image with uploading right?

**Review by yunho7687 — CHANGES_REQUESTED** [review]

File: client/src/components/ui/Question/preview-modal.tsx (hunk 1 above)
Comment (loklokyx) [reply client/src/components/ui/Question/preview-modal.tsx:18]: Thanks for the feedback. The `LatexInput` component is just a wrapper around the `Latex` component, allowing us to render LaTeX content with a customizable `className`.

```javascript
function LatexInput({ className, ...props }: LatexInputProps) {
  return (
    <div
      className={cn(
        "flex h-auto w-auto items-center justify-center text-pretty",
        className,
      )}
    >
      <Latex {...props} />
    </div>
  );
}
```

Previously, each file using `Latex` had to manually import the CSS:  
```javascript
import "katex/dist/katex.min.css";
import Latex from "react-latex-next";
```

One file(`generic-quiz.tsx`) accidentally missed the CSS import, causing a **duplicate rendering issue** (which you reported last time). To avoid this problem, I created the `LatexInput` component so we only need to use this component without worrying about repeated imports.

Comment (yunho7687) [reply client/src/components/ui/Question/preview-modal.tsx:18]: thanks for the explanation and well done!

**Review by yunho7687 — APPROVED** [review]
well done, thank you!
